/**
 * @File Name          : FirstApexClass.cls
 * @Description        : 
 * @Author             : auyon.bhattacharya@somedomain.com
 * @Group              : 
 * @Last Modified By   : phUser@phDomain.com
 * @Last Modified On   : 2/13/2019, 11:47:32 AM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    2/13/2019, 11:46:54 AM   uyon.bhattacharya@somedomain.com     Initial Version
**/
class FirstApexClass {
    doSomeWork(String strList){


        return ('Did Something');
    }    
}
